"""Test Migrate

Revision ID: 361938a97db8
Revises: 
Create Date: 2025-04-12 14:30:40.884977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361938a97db8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('occurrence', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('occurrence', sa.String(length=50), nullable=False),
    sa.Column('dedicated_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_spend_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('security_question_one', sa.String(length=100), nullable=False),
    sa.Column('security_answer_one', sa.String(length=100), nullable=False),
    sa.Column('security_question_two', sa.String(length=100), nullable=True),
    sa.Column('security_answer_two', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('expenses')
    op.drop_table('earnings')
    # ### end Alembic commands ###
