"""Increase user security sizes

Revision ID: 3c57e96bc249
Revises: fce6e8965809
Create Date: 2025-04-12 16:26:30.279116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c57e96bc249'
down_revision = 'fce6e8965809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('security_question_one',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=400),
               nullable=False)
        batch_op.alter_column('security_answer_one',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=400),
               nullable=False)
        batch_op.alter_column('security_question_two',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=True)
        batch_op.alter_column('security_answer_two',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('security_answer_two',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('security_question_two',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('security_answer_one',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('security_question_one',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
