"""empty message

Revision ID: 41d5057aa2e3
Revises: 361938a97db8
Create Date: 2025-04-12 15:36:53.451162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d5057aa2e3'
down_revision = '361938a97db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('security_question_one',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('security_answer_one',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('security_answer_one',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('security_question_one',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
