"""change nulls logic

Revision ID: 9c2f38c134c6
Revises: 26b8b9ae70a6
Create Date: 2025-04-13 16:32:11.904229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2f38c134c6'
down_revision = '26b8b9ae70a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earnings', schema=None) as batch_op:
        batch_op.alter_column('occurrence',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('occurrence',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('dedicated_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('actual_spend_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('actual_spend_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('dedicated_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('occurrence',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('earnings', schema=None) as batch_op:
        batch_op.alter_column('occurrence',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
